language: python
sudo: required
services:
- docker
python:

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - docker-compose build

before_script:
  # We will run a postgres service into docker, so wee need to stop the postgres service
  - sudo service postgresql stop
script:
  - docker-compose run web coverage run source/apiVolontaria/manage.py test
  - docker-compose run web pycodestyle --config=.pycodestylerc .

after_success:
  - docker-compose run -e TRAVIS_JOB_ID -e TRAVIS_BRANCH -e TRAVIS api coveralls