language: python

python:
  - 3.6

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install --upgrade pip
  - pip install --use-feature=2020-resolver -r requirements.txt
  - pip install coveralls
  - pip install pycodestyle

script:
 - docker-compose build
 - docker-compose run web coverage run --source=api_volontaria --omit=env/* manage.py test
 - docker-compose run web pycodestyle --config=.pycodestylerc .

after_success:
  coveralls
