services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    restart: always
    env_file: .env
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
    image: web
    build: 
      context: ./api
    command: >
      bash -c "python wait_for_postgres.py &&
        ./manage.py migrate &&
        ./manage.py collectstatic --noinput &&
        ./manage.py runserver --insecure 0.0.0.0:8000"
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    image: minidocks/mkdocs:latest
    restart: always
    command: "mkdocs serve"
    volumes:
      - ./documentation:/code
    working_dir: /code
    ports:
      - "8010:8010"
