# Generated by Django 2.2.12 on 2022-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='type_email',
            field=models.TextField(verbose_name='Type email'),
        ),
    ]
