# Generated by Django 2.2.12 on 2022-07-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='latitude',
            field=models.FloatField(blank=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='longitude',
            field=models.FloatField(blank=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Cell', verbose_name='Évenement'),
        ),
    ]
