# Generated by Django 2.2.12 on 2022-07-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20220704_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Cell', verbose_name='Place'),
        ),
    ]
